"""
Configuration file for health platform integrations
Contains API keys, credentials, and other settings needed for integrating with external health platforms
"""

import os

# Fitbit API configuration
FITBIT_CONFIG = {
    'client_id':
    os.environ.get('FITBIT_CLIENT_ID', '23Q88S'),
    'client_secret':
    os.environ.get('FITBIT_CLIENT_SECRET', '255d300e5671fe7667ade5d12a83ee85'),
    'redirect_uri':
    os.environ.get(
        'FITBIT_REDIRECT_URI',
        'http://localhost:5000/health/oauth_callback'
    ),
    'authorize_url':
    'https://www.fitbit.com/oauth2/authorize',
    'token_url':
    'https://api.fitbit.com/oauth2/token',
    'scope':
    'activity heartrate sleep weight profile electrocardiogram cardio_fitness irregular_rhythm_notifications location nutrition oxygen_saturation respiratory_rate temperature',
    'api_base_url':
    'https://api.fitbit.com'
}

# Mapping of Fitbit endpoints to VitalSignType
FITBIT_ENDPOINTS = {
    'heart_rate': {
        'endpoint': '/1/user/-/activities/heart/date/today/1d/1min.json',
        'base_endpoint': '/1/user/-/activities/heart/date',
        'daily_endpoint': '/1/user/-/activities/heart/date/{date}/1d.json',
        'intraday_endpoint': '/1/user/-/activities/heart/date/{date}/1d/1min.json',
        'range_endpoint': '/1/user/-/activities/heart/date/{start}/{end}.json',
        'detail_level': '1min',
        'max_range_days': 30,  # Limiti imposti da Fitbit
        'response_key': 'activities-heart',
        'intraday_response_key': 'activities-heart-intraday',
        'dataset_key': 'dataset',
        'value_key': 'value',
        'timestamp_key': 'time',
        'timestamp_format': '%H:%M:%S',
        'unit': 'bpm',
        'description': 'Frequenza cardiaca',
        'oauth_scope': 'heartrate',
        'default_aggregation': 'avg',
        'value_transform': lambda x: x,
        'chart_color': '#FF5252'
    },
    'steps': {
        'endpoint': '/1/user/-/activities/steps/date/today/1w.json',
        'base_endpoint': '/1/user/-/activities/steps/date',
        'daily_endpoint': '/1/user/-/activities/steps/date/{date}/1d.json',
        'intraday_endpoint': '/1/user/-/activities/steps/date/{date}/1d/1min.json',
        'range_endpoint': '/1/user/-/activities/steps/date/{start}/{end}.json',
        'detail_level': '1min',
        'max_range_days': 100,
        'response_key': 'activities-steps',
        'intraday_response_key': 'activities-steps-intraday',
        'dataset_key': 'dataset',
        'value_key': 'value',
        'timestamp_key': 'dateTime',
        'intraday_timestamp_key': 'time',
        'timestamp_format': '%H:%M:%S',
        'unit': 'steps',
        'description': 'Passi',
        'oauth_scope': 'activity',
        'default_aggregation': 'sum',
        'value_transform': lambda x: x,
        'chart_color': '#2196F3'
    },
    'calories': {
        'endpoint': '/1/user/-/activities/calories/date/today/1w.json',
        'base_endpoint': '/1/user/-/activities/calories/date',
        'daily_endpoint': '/1/user/-/activities/calories/date/{date}/1d.json',
        'intraday_endpoint': '/1/user/-/activities/calories/date/{date}/1d/1min.json',
        'range_endpoint': '/1/user/-/activities/calories/date/{start}/{end}.json',
        'detail_level': '1min',
        'max_range_days': 100,
        'response_key': 'activities-calories',
        'intraday_response_key': 'activities-calories-intraday',
        'dataset_key': 'dataset',
        'value_key': 'value',
        'timestamp_key': 'dateTime',
        'intraday_timestamp_key': 'time',
        'timestamp_format': '%H:%M:%S',
        'unit': 'kcal',
        'description': 'Calorie',
        'oauth_scope': 'activity',
        'default_aggregation': 'sum',
        'value_transform': lambda x: x,
        'chart_color': '#FF9800'
    },
    'distance': {
        'endpoint': '/1/user/-/activities/distance/date/today/1w.json',
        'base_endpoint': '/1/user/-/activities/distance/date',
        'daily_endpoint': '/1/user/-/activities/distance/date/{date}/1d.json',
        'intraday_endpoint': '/1/user/-/activities/distance/date/{date}/1d/1min.json',
        'range_endpoint': '/1/user/-/activities/distance/date/{start}/{end}.json',
        'detail_level': '1min',
        'max_range_days': 100,
        'response_key': 'activities-distance',
        'intraday_response_key': 'activities-distance-intraday',
        'dataset_key': 'dataset',
        'value_key': 'value',
        'timestamp_key': 'dateTime',
        'intraday_timestamp_key': 'time',
        'timestamp_format': '%H:%M:%S',
        'unit': 'km',
        'description': 'Distanza',
        'oauth_scope': 'activity',
        'default_aggregation': 'sum',
        'value_transform': lambda x: x,
        'chart_color': '#4CAF50'
    },
    'active_minutes': {
        'endpoint': '/1/user/-/activities/minutesVeryActive/date/today/1w.json',
        'base_endpoint': '/1/user/-/activities/minutesVeryActive/date',
        'daily_endpoint': '/1/user/-/activities/minutesVeryActive/date/{date}/1d.json',
        'range_endpoint': '/1/user/-/activities/minutesVeryActive/date/{start}/{end}.json',
        'max_range_days': 100,
        'response_key': 'activities-minutesVeryActive',
        'value_key': 'value',
        'timestamp_key': 'dateTime',
        'unit': 'min',
        'description': 'Minuti attivi',
        'oauth_scope': 'activity',
        'default_aggregation': 'sum',
        'value_transform': lambda x: x,
        'chart_color': '#9C27B0'
    },
    'sleep_duration': {
        'endpoint': '/1.2/user/-/sleep/date/today.json',
        'base_endpoint': '/1.2/user/-/sleep/date',
        'daily_endpoint': '/1.2/user/-/sleep/date/{date}.json',
        'range_endpoint': '/1.2/user/-/sleep/date/{start}/{end}.json',
        'max_range_days': 100,
        'response_key': 'sleep',
        'value_key': 'minutesAsleep',
        'timestamp_key': 'startTime',
        'unit': 'min',
        'description': 'Sonno',
        'oauth_scope': 'sleep',
        'default_aggregation': 'avg',
        'value_transform': lambda x: x / 60,  # convert minutes to hours
        'chart_color': '#3F51B5'
    },
    'floors_climbed': {
        'endpoint': '/1/user/-/activities/floors/date/today/1w.json',
        'base_endpoint': '/1/user/-/activities/floors/date',
        'daily_endpoint': '/1/user/-/activities/floors/date/{date}/1d.json',
        'intraday_endpoint': '/1/user/-/activities/floors/date/{date}/1d/1min.json',
        'range_endpoint': '/1/user/-/activities/floors/date/{start}/{end}.json',
        'detail_level': '1min',
        'max_range_days': 100,
        'response_key': 'activities-floors',
        'intraday_response_key': 'activities-floors-intraday',
        'dataset_key': 'dataset',
        'value_key': 'value',
        'timestamp_key': 'dateTime',
        'intraday_timestamp_key': 'time',
        'timestamp_format': '%H:%M:%S',
        'unit': 'floors',
        'description': 'Piani saliti',
        'oauth_scope': 'activity',
        'default_aggregation': 'sum',
        'value_transform': lambda x: x,
        'chart_color': '#795548'
    },
    'elevation': {
        'endpoint': '/1/user/-/activities/elevation/date/today/1w.json',
        'base_endpoint': '/1/user/-/activities/elevation/date',
        'daily_endpoint': '/1/user/-/activities/elevation/date/{date}/1d.json',
        'intraday_endpoint': '/1/user/-/activities/elevation/date/{date}/1d/1min.json',
        'range_endpoint': '/1/user/-/activities/elevation/date/{start}/{end}.json',
        'detail_level': '1min',
        'max_range_days': 100,
        'response_key': 'activities-elevation',
        'intraday_response_key': 'activities-elevation-intraday',
        'dataset_key': 'dataset',
        'value_key': 'value',
        'timestamp_key': 'dateTime',
        'intraday_timestamp_key': 'time',
        'timestamp_format': '%H:%M:%S',
        'unit': 'm',
        'description': 'Dislivello',
        'oauth_scope': 'activity',
        'default_aggregation': 'sum',
        'value_transform': lambda x: x,
        'chart_color': '#795548'
    },
    'weight': {
        'endpoint': '/1/user/-/body/log/weight/date/today/1m.json',
        'base_endpoint': '/1/user/-/body/log/weight/date',
        'daily_endpoint': '/1/user/-/body/log/weight/date/{date}.json',
        'range_endpoint': '/1/user/-/body/log/weight/date/{start}/{end}.json',
        'max_range_days': 31,
        'response_key': 'weight',
        'value_key': 'weight',
        'timestamp_key': 'date',
        'unit': 'kg',
        'description': 'Peso',
        'oauth_scope': 'weight',
        'default_aggregation': 'avg',
        'value_transform': lambda x: x,
        'chart_color': '#607D8B'
    },
    'activity_calories': {
        'endpoint': '/1/user/-/activities/activityCalories/date/today/1w.json',
        'base_endpoint': '/1/user/-/activities/activityCalories/date',
        'daily_endpoint': '/1/user/-/activities/activityCalories/date/{date}/1d.json',
        'range_endpoint': '/1/user/-/activities/activityCalories/date/{start}/{end}.json',
        'max_range_days': 100,
        'response_key': 'activities-activityCalories',
        'value_key': 'value',
        'timestamp_key': 'dateTime',
        'unit': 'kcal',
        'description': 'Calorie da attività',
        'oauth_scope': 'activity',
        'default_aggregation': 'sum',
        'value_transform': lambda x: x,
        'chart_color': '#FF5722'
    },
    'calories_bmr': {
        'endpoint': '/1/user/-/activities/caloriesBMR/date/today/1w.json',
        'base_endpoint': '/1/user/-/activities/caloriesBMR/date',
        'daily_endpoint': '/1/user/-/activities/caloriesBMR/date/{date}/1d.json',
        'range_endpoint': '/1/user/-/activities/caloriesBMR/date/{start}/{end}.json',
        'max_range_days': 100,
        'response_key': 'activities-caloriesBMR',
        'value_key': 'value',
        'timestamp_key': 'dateTime',
        'unit': 'kcal',
        'description': 'Metabolismo basale',
        'oauth_scope': 'activity',
        'default_aggregation': 'avg',
        'value_transform': lambda x: x,
        'chart_color': '#FF5722'
    },
    'minutes_sedentary': {
        'endpoint': '/1/user/-/activities/minutesSedentary/date/today/1w.json',
        'base_endpoint': '/1/user/-/activities/minutesSedentary/date',
        'daily_endpoint': '/1/user/-/activities/minutesSedentary/date/{date}/1d.json',
        'range_endpoint': '/1/user/-/activities/minutesSedentary/date/{start}/{end}.json',
        'max_range_days': 100,
        'response_key': 'activities-minutesSedentary',
        'value_key': 'value',
        'timestamp_key': 'dateTime',
        'unit': 'min',
        'description': 'Minuti sedentari',
        'oauth_scope': 'activity',
        'default_aggregation': 'sum',
        'value_transform': lambda x: x,
        'chart_color': '#9E9E9E'
    },
    'minutes_lightly_active': {
        'endpoint': '/1/user/-/activities/minutesLightlyActive/date/today/1w.json',
        'base_endpoint': '/1/user/-/activities/minutesLightlyActive/date',
        'daily_endpoint': '/1/user/-/activities/minutesLightlyActive/date/{date}/1d.json',
        'range_endpoint': '/1/user/-/activities/minutesLightlyActive/date/{start}/{end}.json',
        'max_range_days': 100,
        'response_key': 'activities-minutesLightlyActive',
        'value_key': 'value',
        'timestamp_key': 'dateTime',
        'unit': 'min',
        'description': 'Attività leggera',
        'oauth_scope': 'activity',
        'default_aggregation': 'sum',
        'value_transform': lambda x: x,
        'chart_color': '#8BC34A'
    },
    'minutes_fairly_active': {
        'endpoint': '/1/user/-/activities/minutesFairlyActive/date/today/1w.json',
        'base_endpoint': '/1/user/-/activities/minutesFairlyActive/date',
        'daily_endpoint': '/1/user/-/activities/minutesFairlyActive/date/{date}/1d.json',
        'range_endpoint': '/1/user/-/activities/minutesFairlyActive/date/{start}/{end}.json',
        'max_range_days': 100,
        'response_key': 'activities-minutesFairlyActive',
        'value_key': 'value',
        'timestamp_key': 'dateTime',
        'unit': 'min',
        'description': 'Attività moderata',
        'oauth_scope': 'activity',
        'default_aggregation': 'sum',
        'value_transform': lambda x: x,
        'chart_color': '#FFC107'
    },
    'calories_in': {
        'endpoint': '/1/user/-/foods/log/caloriesIn/date/today/1w.json',
        'base_endpoint': '/1/user/-/foods/log/caloriesIn/date',
        'daily_endpoint': '/1/user/-/foods/log/caloriesIn/date/{date}.json',
        'range_endpoint': '/1/user/-/foods/log/caloriesIn/date/{start}/{end}.json',
        'max_range_days': 365,
        'response_key': 'foods-log-caloriesIn',
        'value_key': 'value',
        'timestamp_key': 'dateTime',
        'unit': 'kcal',
        'description': 'Calorie assunte',
        'oauth_scope': 'nutrition',
        'default_aggregation': 'sum',
        'value_transform': lambda x: x,
        'chart_color': '#F44336'
    },
    'water': {
        'endpoint': '/1/user/-/foods/log/water/date/today/1w.json',
        'base_endpoint': '/1/user/-/foods/log/water/date',
        'daily_endpoint': '/1/user/-/foods/log/water/date/{date}.json',
        'range_endpoint': '/1/user/-/foods/log/water/date/{start}/{end}.json',
        'max_range_days': 365,
        'response_key': 'foods-log-water',
        'value_key': 'value',
        'timestamp_key': 'dateTime',
        'unit': 'ml',
        'description': 'Consumo d\'acqua',
        'oauth_scope': 'nutrition',
        'default_aggregation': 'sum',
        'value_transform': lambda x: x,
        'chart_color': '#03A9F4'
    },
    'breathing_rate': {
        'endpoint': '/1/user/-/br/date/today/1w.json',
        'base_endpoint': '/1/user/-/br/date',
        'daily_endpoint': '/1/user/-/br/date/{date}.json',
        'range_endpoint': '/1/user/-/br/date/{start}/{end}.json',
        'max_range_days': 30,
        'response_key': 'br',
        'value_key': 'value.breathingRate',
        'timestamp_key': 'dateTime',
        'unit': 'resp/min',
        'description': 'Frequenza respiratoria',
        'oauth_scope': 'respiratory_rate',
        'default_aggregation': 'avg',
        'value_transform': lambda x: x,
        'chart_color': '#00BCD4'
    },
    'oxygen_saturation': {
        'endpoint': '/1/user/-/spo2/date/today/1w.json',
        'base_endpoint': '/1/user/-/spo2/date',
        'daily_endpoint': '/1/user/-/spo2/date/{date}.json',
        'range_endpoint': '/1/user/-/spo2/date/{start}/{end}.json',
        'max_range_days': 30,
        'response_key': 'spo2',
        'value_key': 'value.avg',
        'timestamp_key': 'dateTime',
        'unit': '%',
        'description': 'Ossigenazione',
        'oauth_scope': 'oxygen_saturation',
        'default_aggregation': 'avg',
        'value_transform': lambda x: x,
        'chart_color': '#3F51B5'
    }
}
