"""Add health platform integration

Revision ID: cc82b6077aee
Revises: 
Create Date: 2025-04-23 13:03:50.287865

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cc82b6077aee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('health_platform_connection')
    with op.batch_alter_table('health_platform_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform', sa.Enum('FITBIT', 'GOOGLE_FIT', 'APPLE_HEALTH', name='healthplatform'), nullable=False))
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('connected_platform', sa.Enum('FITBIT', 'GOOGLE_FIT', 'APPLE_HEALTH', name='healthplatform'), nullable=True))
        batch_op.add_column(sa.Column('platform_access_token', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('platform_refresh_token', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('platform_token_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('platform_token_expires_at')
        batch_op.drop_column('platform_refresh_token')
        batch_op.drop_column('platform_access_token')
        batch_op.drop_column('connected_platform')

    with op.batch_alter_table('health_platform_link', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_column('platform')

    op.create_table('health_platform_connection',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('platform_type', postgresql.ENUM('FITBIT', 'GOOGLE_FIT', 'APPLE_HEALTH', name='healthplatform'), autoincrement=False, nullable=False),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], name='health_platform_connection_patient_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='health_platform_connection_pkey')
    )
    # ### end Alembic commands ###
