site_name: VitaLink Documentation
site_description: Documentation of VitaLink API
site_author: Andrea Roggeri
use_directory_urls: false
theme:
  name: material
  language: it
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate

repo_name: VitaLink
repo_url: https://github.com/andrearoggeri22/VitaLink

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - admonition
  - toc:
      permalink: true

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [../../../app] 
          options:
            members_order: source
            show_source: true
            show_signature_annotations: true
            docstring_style: google
            show_if_no_docstring: true
            show_signature: true
            heading_level: 3

nav:
  - Home: index.md
  - Modules:
      - API: modules/api.md
      - App: modules/app.md
      - Audit: modules/audit.md
      - Auth: modules/auth.md
      - Compile Translations: modules/compile_translations.md
      - Email Utils: modules/email_utils.md
      - Health Platforms: modules/health_platforms.md
      - Health Platforms Config: modules/health_platforms_config.md
      - Language: modules/language.md
      - Main: modules/main.md
      - Migrate: modules/migrate.md
      - Models: modules/models.md
      - Observations: modules/observations.md
      - Reports: modules/reports.md
      - Utils: modules/utils.md
      - Views: modules/views.md
