name: Static Code Analysis and Report

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout del repository
    - name: Checkout Repository
      uses: actions/checkout@v4

    # 2. Installazione di Python e dipendenze
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint radon bandit flake8 coverage

    # 3. Analisi con Pylint
    - name: Run Pylint
      run: |
        pylint app > pylint-report.txt || true

    # 4. Calcolo complessità ciclomatica con Radon
    - name: Run Radon Cyclomatic Complexity
      run: |
        radon cc app -s -n B > radon-report.txt || true

    # 5. Analisi di sicurezza con Bandit
    - name: Run Bandit Security Analysis
      run: |
        bandit -r app > bandit-report.txt || true

    # 6. Controllo di conformità PEP8 con Flake8
    - name: Run Flake8 Style Check
      run: |
        flake8 app > flake8-report.txt || true

    # 7. Misurazione della copertura del codice con Coverage.py
    - name: Run Coverage Analysis
      run: |
        coverage run -m pytest
        coverage report > coverage-report.txt
        coverage html

    # 8. Installazione di Cloc per statistiche sulle righe di codice
    - name: Install Cloc
      run: sudo apt-get install -y cloc

    - name: Run Cloc
      run: |
        cloc . --out=cloc-report.txt

    # 9. Analisi di duplicazione del codice con jscpd
    - name: Run Code Duplication Check (jscpd)
      run: |
        npx jscpd --reporters text --output jscpd-report.txt .

    # 10. Installazione di ESLint per JavaScript e HTML
    - name: Install ESLint
      run: |
        npm install -g eslint

    - name: Run ESLint
      run: |
        eslint . > eslint-report.txt || true

    # 11. Generazione del report HTML
    - name: Generate HTML Report
      run: |
        mkdir -p analysis
        echo "<html><head><title>Static Analysis Report</title>" > analysis/index.html
        echo "<style>" >> analysis/index.html
        echo "body { font-family: Arial, sans-serif; line-height: 1.6; padding: 20px; }" >> analysis/index.html
        echo "nav { background: #333; color: white; padding: 10px; }" >> analysis/index.html
        echo "nav a { color: white; margin: 0 15px; text-decoration: none; }" >> analysis/index.html
        echo ".section { margin-bottom: 20px; }" >> analysis/index.html
        echo "</style></head><body>" >> analysis/index.html
        echo "<nav><a href='#pylint'>Pylint Report</a> | <a href='#radon'>Cyclomatic Complexity</a> | <a href='#bandit'>Bandit Report</a> | <a href='#flake8'>Flake8 Report</a> | <a href='#coverage'>Coverage Report</a> | <a href='#cloc'>Cloc Report</a> | <a href='#jscpd'>Code Duplication</a> | <a href='#eslint'>ESLint Report</a></nav>" >> analysis/index.html
        echo "<h1>Static Analysis Report</h1>" >> analysis/index.html
        echo "<div class='section' id='pylint'><h2>Pylint Report</h2><pre>" >> analysis/index.html
        cat pylint-report.txt >> analysis/index.html
        echo "</pre></div>" >> analysis/index.html
        echo "<div class='section' id='radon'><h2>Cyclomatic Complexity</h2><pre>" >> analysis/index.html
        cat radon-report.txt >> analysis/index.html
        echo "</pre></div>" >> analysis/index.html
        echo "<div class='section' id='bandit'><h2>Bandit Report</h2><pre>" >> analysis/index.html
        cat bandit-report.txt >> analysis/index.html
        echo "</pre></div>" >> analysis/index.html
        echo "<div class='section' id='flake8'><h2>Flake8 Report</h2><pre>" >> analysis/index.html
        cat flake8-report.txt >> analysis/index.html
        echo "</pre></div>" >> analysis/index.html
        echo "<div class='section' id='coverage'><h2>Coverage Report</h2><pre>" >> analysis/index.html
        cat coverage-report.txt >> analysis/index.html
        echo "</pre></div>" >> analysis/index.html
        echo "<div class='section' id='cloc'><h2>Cloc Report</h2><pre>" >> analysis/index.html
        cat cloc-report.txt >> analysis/index.html
        echo "</pre></div>" >> analysis/index.html
        echo "<div class='section' id='jscpd'><h2>Code Duplication Report</h2><pre>" >> analysis/index.html
        cat jscpd-report.txt >> analysis/index.html
        echo "</pre></div>" >> analysis/index.html
        echo "<div class='section' id='eslint'><h2>ESLint Report</h2><pre>" >> analysis/index.html
        cat eslint-report.txt >> analysis/index.html
        echo "</pre></div>" >> analysis/index.html
        echo "</body></html>" >> analysis/index.html

    # 12. Pubblicazione su GitHub Pages
    - name: Deploy Analysis to gh-pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./analysis
        destination_dir: analysis
