name: Static Code Analysis and Report

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      env:
        DATABASE_URL: "sqlite:///test_healthcare.db"
        CLOUD_RUN_ENVIRONMENT: "false"
        FLASK_APP: "app:app"
        SESSION_SECRET: "noKey"
        PORT: "5000"
        HOST: "0.0.0.0"
        DEBUG: "true"
        JWT_SECRET_KEY: "noKey"
        FITBIT_CLIENT_ID: "noKey"
        FITBIT_CLIENT_SECRET: "noKey"
        FITBIT_REDIRECT_URI: "noKey"
        MJ_APIKEY: "noKey"
        MJ_APIKEY_SECRET: "noKey"
        LOG_LEVEL: "INFO"
        EMAIL_SENDER: "test@test.com"
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install pytest coverage radon pipdeptree

    - name: Run Coverage Analysis
      env:
        DATABASE_URL: "sqlite:///test_healthcare.db"
        CLOUD_RUN_ENVIRONMENT: "false"
        FLASK_APP: "app:app"
        SESSION_SECRET: "noKey"
        PORT: "5000"
        HOST: "0.0.0.0"
        DEBUG: "true"
        JWT_SECRET_KEY: "noKey"
        FITBIT_CLIENT_ID: "noKey"
        FITBIT_CLIENT_SECRET: "noKey"
        FITBIT_REDIRECT_URI: "noKey"
        MJ_APIKEY: "noKey"
        MJ_APIKEY_SECRET: "noKey"
        LOG_LEVEL: "INFO"
        EMAIL_SENDER: "test@test.com"
      run: |
        coverage run -m pytest
        coverage report > coverage-report.txt
        coverage html

    - name: Run Radon Analysis
      run: |
        radon cc app -s -n B > radon-cyclomatic-report.txt
        radon mi app > radon-maintainability-report.txt
        radon hal app > radon-halstead-report.txt

    - name: Run Pipdeptree
      run: |
        pipdeptree > pipdeptree-report.txt

    - name: Install Cloc
      run: sudo apt-get install -y cloc

    - name: Run Cloc
      run: |
        cloc . --out=cloc-report.txt

    - name: Generate HTML Report
      run: |
        mkdir -p analysis
        echo "<html><head><title>Static Analysis Report</title>" > analysis/index.html
        echo "<style>" >> analysis/index.html
        echo "body { font-family: Arial, sans-serif; line-height: 1.6; padding: 20px; }" >> analysis/index.html
        echo "nav { background: #333; color: white; padding: 10px; }" >> analysis/index.html
        echo "nav a { color: white; margin: 0 15px; text-decoration: none; }" >> analysis/index.html
        echo ".section { margin-bottom: 20px; }" >> analysis/index.html
        echo "</style></head><body>" >> analysis/index.html
        echo "<nav><a href='#coverage'>Coverage Report</a> | <a href='#cloc'>Cloc Report</a> | <a href='#cyclomatic'>Cyclomatic Complexity</a> | <a href='#halstead'>Halstead Metrics</a> | <a href='#mi'>Maintainability Index</a> | <a href='#pipdeptree'>Pipdeptree</a></nav>" >> analysis/index.html
        echo "<h1>Static Analysis Report</h1>" >> analysis/index.html
        echo "<div class='section' id='coverage'><h2>Coverage Report</h2><pre>" >> analysis/index.html
        cat coverage-report.txt >> analysis/index.html
        echo "</pre></div>" >> analysis/index.html
        echo "<div class='section' id='cloc'><h2>Cloc Report</h2><pre>" >> analysis/index.html
        cat cloc-report.txt >> analysis/index.html
        echo "</pre></div>" >> analysis/index.html
        echo "<div class='section' id='cyclomatic'><h2>Cyclomatic Complexity</h2><pre>" >> analysis/index.html
        cat radon-cyclomatic-report.txt >> analysis/index.html
        echo "</pre></div>" >> analysis/index.html
        echo "<div class='section' id='halstead'><h2>Halstead Metrics</h2><pre>" >> analysis/index.html
        cat radon-halstead-report.txt >> analysis/index.html
        echo "</pre></div>" >> analysis/index.html
        echo "<div class='section' id='mi'><h2>Maintainability Index</h2><pre>" >> analysis/index.html
        cat radon-maintainability-report.txt >> analysis/index.html
        echo "</pre></div>" >> analysis/index.html
        echo "<div class='section' id='pipdeptree'><h2>Pipdeptree Report</h2><pre>" >> analysis/index.html
        cat pipdeptree-report.txt >> analysis/index.html
        echo "</pre></div>" >> analysis/index.html
        echo "</body></html>" >> analysis/index.html

    - name: Deploy Analysis to gh-pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./analysis
        destination_dir: analysis
