name: Static Code Analysis and Report

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout del repository
    - name: Checkout Repository
      uses: actions/checkout@v4

    # 2. Configurazione di Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # 3. Installazione delle dipendenze
    - name: Install dependencies
      env:
        DATABASE_URL: "sqlite:///test_healthcare.db"
        CLOUD_RUN_ENVIRONMENT: "false"
        FLASK_APP: "app:app"
        SESSION_SECRET: "noKey"
        PORT: "5000"
        HOST: "0.0.0.0"
        DEBUG: "true"
        JWT_SECRET_KEY: "noKey"
        FITBIT_CLIENT_ID: "noKey"
        FITBIT_CLIENT_SECRET: "noKey"
        FITBIT_REDIRECT_URI: "noKey"
        MJ_APIKEY: "noKey"
        MJ_APIKEY_SECRET: "noKey"
        LOG_LEVEL: "INFO"
        EMAIL_SENDER: "test@test.com"
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install pytest coverage

    # 4. Esecuzione dei test con Coverage.py
    - name: Run Coverage Analysis
      env:
        DATABASE_URL: "sqlite:///test_healthcare.db"
        CLOUD_RUN_ENVIRONMENT: "false"
        FLASK_APP: "app:app"
        SESSION_SECRET: "noKey"
        PORT: "5000"
        HOST: "0.0.0.0"
        DEBUG: "true"
        JWT_SECRET_KEY: "noKey"
        FITBIT_CLIENT_ID: "noKey"
        FITBIT_CLIENT_SECRET: "noKey"
        FITBIT_REDIRECT_URI: "noKey"
        MJ_APIKEY: "noKey"
        MJ_APIKEY_SECRET: "noKey"
        LOG_LEVEL: "INFO"
        EMAIL_SENDER: "test@test.com"
      run: |
        coverage run -m pytest
        coverage report > coverage-report.txt
        coverage html

    # 5. Installazione di Cloc per statistiche sulle righe di codice
    - name: Install Cloc
      run: sudo apt-get install -y cloc

    - name: Run Cloc
      run: |
        cloc . --out=cloc-report.txt

    # 6. Generazione del report HTML
    - name: Generate HTML Report
      run: |
        mkdir -p analysis
        echo "<html><head><title>Static Analysis Report</title>" > analysis/index.html
        echo "<style>" >> analysis/index.html
        echo "body { font-family: Arial, sans-serif; line-height: 1.6; padding: 20px; }" >> analysis/index.html
        echo "nav { background: #333; color: white; padding: 10px; }" >> analysis/index.html
        echo "nav a { color: white; margin: 0 15px; text-decoration: none; }" >> analysis/index.html
        echo ".section { margin-bottom: 20px; }" >> analysis/index.html
        echo "</style></head><body>" >> analysis/index.html
        echo "<nav><a href='#coverage'>Coverage Report</a> | <a href='#cloc'>Cloc Report</a></nav>" >> analysis/index.html
        echo "<h1>Static Analysis Report</h1>" >> analysis/index.html
        echo "<div class='section' id='coverage'><h2>Coverage Report</h2><pre>" >> analysis/index.html
        cat coverage-report.txt >> analysis/index.html
        echo "</pre></div>" >> analysis/index.html
        echo "<div class='section' id='cloc'><h2>Cloc Report</h2><pre>" >> analysis/index.html
        cat cloc-report.txt >> analysis/index.html
        echo "</pre></div>" >> analysis/index.html
        echo "</body></html>" >> analysis/index.html

    # 7. Pubblicazione su GitHub Pages
    - name: Deploy Analysis to gh-pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./analysis
        destination_dir: analysis
