name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # Checkout del codice
    - uses: actions/checkout@v4

    # Configurazione di Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' 

    - name: Set environment variables
      env:
        DATABASE_URL: "sqlite:///:memory:"
        CLOUD_RUN_ENVIRONMENT: "false"
        FLASK_APP: "app:app"
        SESSION_SECRET: "noKey"
        PORT: "5000"
        HOST: "0.0.0.0"
        DEBUG: "true"
        JWT_SECRET_KEY: "noKey"
        FITBIT_CLIENT_ID: "noKey"
        FITBIT_CLIENT_SECRET: "noKey"
        FITBIT_REDIRECT_URI: "noKey"
        MJ_APIKEY: "noKey"
        MJ_APIKEY_SECRET: "noKey"
        LOG_LEVEL: "LOG"
        EMAIL_SENDER: "test@test.com"

    # Installazione delle dipendenze
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install pytest
        
    # Esecuzione dei test con pytest
    - name: Run tests
      run: pytest

    # Costruzione dell'immagine Docker
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
