name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # Checkout del codice
    - uses: actions/checkout@v4

    # Configurazione di Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11' 

    # Installazione delle dipendenze
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        
    # Esecuzione dei test con pytest
    - name: Run tests
      run: pytest

    # Costruzione dell'immagine Docker
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
