name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material mkdocstrings  mkdocstrings-python mkdocs-autorefs

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

    - name: Build documentation from docs/code
      working-directory: docs/code
      run: mkdocs build

    - name: Move docs/code/site to a temporary directory
      run: |
        if [ -d "docs/code/site" ]; then
          mv docs/code/site code-site
        else
          echo "Directory 'docs/code/site' not found!"
          exit 1
        fi

    - name: Build documentation from docs/tests
      working-directory: docs/tests
      run: mkdocs build

    - name: Move docs/tests/site to a temporary directory
      run: |
        if [ -d "docs/tests/site" ]; then
          mv docs/tests/site tests-site
        else
          echo "Directory 'docs/tests/site' not found!"
          exit 1
        fi

    - name: Combine documentation
      run: |
        mkdir -p combined-site/code
        mkdir -p combined-site/tests
        mv code-site/* combined-site/code/
        mv tests-site/* combined-site/tests/

    - name: Debug combined site
      run: |
        echo "Combined site structure:"
        tree combined-site

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./combined-site
