name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout del repository
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Configurazione di Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # Installazione delle dipendenze
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material mkdocstrings mkdocstrings-python mkdocs-autorefs

    # Compilazione della documentazione dalla cartella docs/code
    - name: Build documentation from docs/code
      working-directory: docs/code
      run: mkdocs build

    # Spostamento della documentazione dalla cartella docs/code/site
    - name: Move docs/code/site to a temporary directory
      run: |
        mv site ../code-site

    # Compilazione della documentazione dalla cartella docs/tests
    - name: Build documentation from docs/tests
      working-directory: docs/tests
      run: mkdocs build

    # Spostamento della documentazione dalla cartella docs/tests/site
    - name: Move docs/tests/site to a temporary directory
      run: |
        mv site ../tests-site

    # Unione delle due documentazioni in una singola directory
    - name: Combine documentation
      run: |
        mkdir -p combined-site/code
        mkdir -p combined-site/tests
        mv code-site/* combined-site/code/
        mv tests-site/* combined-site/tests/

    # Deploy della documentazione combinata su GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./combined-site  # Pubblica la documentazione combinata
