name: Static Code Analysis

on:
  push:
    branches:
      - main  # Esegui il workflow su ogni commit nel branch "main"
  workflow_dispatch:  # Permette di avviare il workflow manualmente

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    steps:
    # Checkout del repository
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Installazione di Python e dipendenze
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    # Analisi con Pylint
    - name: Run Pylint
      run: |
        pylint app > pylint-report.txt || true

    # Installazione di Cloc per statistiche sulle righe di codice
    - name: Install Cloc
      run: sudo apt-get install -y cloc

    - name: Run Cloc
      run: |
        cloc . --out=cloc-report.txt

    # Analisi con CodeQL
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: python

    - name: Run CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/codeql"

    # Generazione di un report HTML
    - name: Generate HTML Report
      run: |
        echo "<html><head><title>Static Analysis Report</title></head><body>" > analysis-report.html
        echo "<h1>Static Analysis Report</h1>" >> analysis-report.html
        echo "<h2>Pylint Report</h2><pre>" >> analysis-report.html
        cat pylint-report.txt >> analysis-report.html
        echo "</pre>" >> analysis-report.html
        echo "<h2>Cloc Report</h2><pre>" >> analysis-report.html
        cat cloc-report.txt >> analysis-report.html
        echo "</pre>" >> analysis-report.html
        echo "</body></html>" >> analysis-report.html

    # Sposta il report nella directory analysis nel branch gh-pages
    - name: Deploy Analysis to gh-pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./analysis
        destination_dir: analysis
